### PR TITLE
Correct oUnit typo in all .merlin files

### PR DESCRIPTION
**Pull request by daveyarwood**
See: https://github.com/exercism/ocaml/pull/28#issuecomment-353367578

### CODE REVIEW

**Comment by kytrinyx** [comment]
The build is failing with the following:

```
running tests for: prime-factors
+ ocamlfind ocamlopt -linkpkg -g -thread -package oUnit -package core prime_factors.cmx test.cmx -o test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Big_int referenced from prime_factors.cmx
Command exited with code 2.
make[2]: *** [test.native] Error 10
make[1]: *** [test-assignment] Error 2
make: *** [test] Error 1
```

Would you be able to help figure out what's going on here?

**Comment by daveyarwood** [comment]
AFAICT, the issue is the reference to `Big_int` on [this line](https://github.com/exercism/ocaml/blob/3215c8e55cbc3c6667a3905ee37969567fb45244/exercises/prime-factors/example.ml#L5) in the prime-factors exercise example solution.

I'm not too experienced with OCaml, so I don't know too much about why the error is occurring or how to fix it, but I did find this, which looks to be possibly related: https://github.com/janestreet/bignum/issues/3

I would guess that it's not related to the changes in this PR, but I can't say that for certain.

**Comment by daveyarwood** [comment]
If we want to be more certain that it's not due to my changes, I could submit a second PR that's like this one, except I leave the prime-factors exercise alone, and see if the error goes away?

**Comment by kytrinyx** [comment]
> EDIT: Going ahead and trying it.

That's a good idea!

**Comment by kytrinyx** [comment]
Since this is not what is causing the problem, I'm going to go ahead and pull this in. I'll open an issue for the failure.

Thanks for getting this sorted and helping figure out what's going on!

**Pull request merged**
