### PR TITLE
migrate from jbuilder to dune

### LINKED ISSUE #265: Migrate from jbuilder to dune

### PR DESCRIPTION
**Pull request by sbl**
closes #265 

most of this was just renaming files and adjusting conventions for dune.

the only exercise left out was https://github.com/exercism/ocaml/tree/master/exercises/palindrome-products due to reliance on ppx_deriving see https://github.com/ocaml-ppx/ppx_deriving/pull/170

### CODE REVIEW

**Comment by sbl** [comment]
By convention `.merlin` files seem to be ignored https://github.com/github/gitignore/blob/master/OCaml.gitignore#L23 . From my understanding they are auto generated - e.g. in my case with the dune switch the files included absolute paths relevant only to machine.
but if in doubt let someone comment with more experience in that domain.

**Comment by stevejb71** [comment]
If you still get autocomplete, etc, in your IDE with the new files then I'm happy with it.

I'm without PC at the moment, but I'll also be able to check in a couple of weeks time.

**Comment by sbl** [comment]
Still all works fine in `vim`.

**Comment by stevejb71** [comment]
Good stuff... I'll merge.

Thanks again for your help.

**Pull request merged**
