### PR TITLE
Fix TravisCI by using prebuilt opam2 image

### PR DESCRIPTION
**Pull request by marionebl**
As per #308

### CODE REVIEW

**Comment by marionebl** [comment]
The current error seems to stem from the breaking change in base 0.12 described in #301, this time the example implementation is affected. 

I wonder what the reasoning behind this kind of change is, the [janestreet/base](https://github.com/janestreet/base) does not provide context for this change. 

Are breaking changes to be expected from base? Are there any communication channels where one can ask for the context of such changes?

**Comment by marionebl** [comment]
> The current error seems to stem from the breaking change in base 0.12 described in #301, this time the example implementation is affected.

Solved by pinning base to `0.11.1`

**Comment by stevejb71** [comment]
@marionebl Jane Street say not to rely on stability from base until it's 1.0 release. See
 https://opensource.janestreet.com/base/

I don't know if any communication channels exist.

**Comment by sshine** [comment]
You're a hero, Mario!

**Pull request merged**
