### PR TITLE
Fully migrate all exercises to ounit2

### LINKED ISSUE #364: Library not found "oUnit", but renaming to "ounit" fixes it
When I try running tests dune throws an error "Library not found "oUnit", 
but renaming it to "ounit" in dune file fixes it.

I'm on MacOS.
Dune version is 1.11.3
Opam - 2.0.5.

### LINKED ISSUE #442: oUnit is considered on transition to ounit2
From the docs I see that you say to install `ounit`. OUnit2 seems to recommend now to use `ounit2` for the install, and also use `ounit2` rather than `oUnit` on the dune file (as per [OUnit github](https://github.com/gildor478/ounit#transition-to-ounit2))

A related issue seems to be:
https://github.com/exercism/ocaml/issues/364

### PR DESCRIPTION
**Pull request by georgyo**
The rest of the migrating to ounit2

/closes #442
/closes #364

### CODE REVIEW

**Comment by curtisault** [comment]
@georgyo, I was just hitting this last night. I manually changed it to `oUnit2` in the dune file, however, I'm still receiving an error.

image


`opam list` shows I have the following installed:

```
ounit2                2.2.6        OUnit testing framework
```

---

Any ideas?

**Comment by georgyo** [comment]
@curtisault  The biggest different in ounit2 is that the package name is all lowercase. So `oUnit` becomes `ounit2`.

**Comment by curtisault** [comment]
> @curtisault The biggest different in ounit2 is that the package name is all lowercase. So `oUnit` becomes `ounit2`.

I didn't even notice the casing. That did the trick. 

Thank you.

**Review by ErikSchierboom — COMMENTED** [review]
Not sure if you did this already, but could you add test cases to the ocaml-test-runner repo that verify this new setup works with the test runner?

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
