### PR TITLE
triangle: actively ignore cases with float input 

### PR DESCRIPTION
**Pull request by marionebl**

### CODE REVIEW

**Comment by sshine** [comment]
I don't think that this is a good idea.

Here we perform structural equality on floats.

I think the exercise is complicated significantly if we are to introduce rounding-error testing.

I would also say that this is a bug in OCaml. See [Why can't I compare reals in Standard ML?](https://stackoverflow.com/questions/41394992/why-cant-i-compare-reals-in-standard-ml).

**Comment by marionebl** [comment]
> I don't think that this is a good idea.

> Here we perform structural equality on floats.

> I think the exercise is complicated significantly if we are to introduce rounding-error testing.

> I would also say that this is a bug in OCaml. See Why can't I compare reals in Standard ML?.

The test dataset contains floating point numbers though. Should we filter out those test cases then?

**Comment by sshine** [comment]
> The test dataset contains floating point numbers though. Should we filter out those test cases then?

Yes. [`triangle`'s canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json) gives this comment:

          "comments": [
            " Your track may choose to skip this test    ",
            " and deal only with integers if appropriate "
          ],

When exercism/problem-specifications#1518 merges, we can push a change to triangle's canonical tests that changes these comments into an `optional: "floating-point"` and filter based on this in the test generator.

**Comment by marionebl** [comment]
Ok, so filtering cases was more involved than I would have guessed. Anyway - adapted the test-generator as requested.

**Pull request merged**
