### PR TITLE
add devcontainer configuration

### PR DESCRIPTION
**Pull request by marionebl**
This adds configuration for Visual Studio Code Remote - Containers. Using the mentioned extension with this config allows me to develop on the OCaml track in isolation, which helps with avoiding conflicts with other OCaml based projects and maintaining `opam` switches.

Usage:

* Install [VSCode Insiders](https://code.visualstudio.com/insiders/)
* Install [Visual Studio Code Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
* Open the repo root with VSCode Insiders
* On the notification that pops on the lower right corner hit "Reopen in Container"
  
Screenshot 2019-08-03 at 20 55 18

### CODE REVIEW

**Comment by marionebl** [comment]
> So unless some of this relates to deployment (like with Travis and Docker-related configuration), would it be adequate to put those particular files in .gitignore so that your local setup can continue with them without popping up in git status and such?

I'd be okay with this, just some points that might change the equation a bit

* The config files allow a quick-start into development on the track, skipping global OCaml setup, opam switch etc, which might help with allowing people to contribute 
* The files constitute non-trivial work. While I've invested that work, others would have to repeat it to achieve the same benefits
* The config files won't change very often
* There is a weak relation between CI and the config files as they allow you to develop in an environment that is the very same as the docker images used on our CI runs. In my experience having this ready-made execution environment at hand helps a lot with shaking down CI-specific issues that might be hard to reproduce otherwise.

**Comment by sshine** [comment]
OK!

I think we should make development easier, and while I think many potential contributors to the track will already have most of the necessary Ocaml environment up and running, I'm sure we could boost interest in the track by providing an easy work environment. Perhaps, once this PR passes checks, we can move the documentation for installing this work environment into the repo's README.md.

Also, we should totally make a MirageOS exercise. :-D

**Comment by marionebl** [comment]
> Perhaps, once this PR passes checks, we can move the documentation for installing this work environment into the repo's README.md. 

Sounds very good. Might frame this as "skipping the line" / kickstart intro while keeping around the docs for full local setup

> Also, we should totally make a MirageOS exercise. :-D

Excuse my ignorance but I don't understand the reference :(

**Comment by sshine** [comment]
It was a spur-of-the-moment idea that we should create an intro exercise for [MirageOS](https://mirage.io/): Making the track easier to work with for a particular workflow made me think of another Ocaml technology that I'd never gotten into. "How to get started with a certain Ocaml tech stack" is something we could have at the exercise level.

**Comment by sshine** [comment]
@kytrinyx: It says I'm not authorized to merge this pull request.

I thought that I was an Ocaml maintainer.

Are the Exercism organization groups on GitHub changing layout?

**Comment by kytrinyx** [comment]
> I thought that I was an Ocaml maintainer.

I thought so too.

> Are the Exercism organization groups on GitHub changing layout?

I'm sorry I don't understand the question. I've not made any changes aside from adding people to teams.

**Comment by kytrinyx** [comment]
@sshine You are an ocaml maintainer, and the ocaml team has write access to this repo. You are not allowed to merge?

**Comment by marionebl** [comment]
@sshine @kytrinyx Any chance to unblock us?

**Comment by sshine** [comment]
@kytrinyx, @ihid: No, apparently I'm not authorized to merge this pull request. Screenshot:

github-merging-blocked-to-authorized-users

**Comment by iHiD** [comment]
I think I've unblocked this. The branch protection settings weird strange on this. Can you merge now @sshine?

**Comment by marionebl** [comment]
Apparently I can merge approved PRs now, going ahead.

Thanks @iHiD

**Comment by iHiD** [comment]
Great. Thanks for confirming!

**Pull request merged**
